// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID        string `json:"_id"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	UserID    string `json:"userId"`
	CreatedOn string `json:"createdOn"`
	UpdatedOn string `json:"updatedOn"`
}

type NewAccount struct {
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Name      string    `json:"name"`
	Jobtitle  string    `json:"jobtitle"`
	Age       int       `json:"age"`
	City      string    `json:"city"`
	Hobbies   []*string `json:"hobbies"`
	CreatedOn *string   `json:"createdOn"`
	UpdatedOn *string   `json:"updatedOn"`
}

type NewUser struct {
	Name      string    `json:"name"`
	Jobtitle  string    `json:"jobtitle"`
	Age       int       `json:"age"`
	City      string    `json:"city"`
	Hobbies   []*string `json:"hobbies"`
	AccountID *string   `json:"accountId"`
	CreatedOn *string   `json:"createdOn"`
	UpdatedOn *string   `json:"updatedOn"`
}

type UpdateAccount struct {
	ID        string  `json:"_id"`
	Email     *string `json:"email"`
	Password  *string `json:"password"`
	UpdatedOn *string `json:"updatedOn"`
}

type UpdateUser struct {
	ID        string    `json:"_id"`
	Name      *string   `json:"name"`
	Jobtitle  *string   `json:"jobtitle"`
	Age       *int      `json:"age"`
	City      *string   `json:"city"`
	Hobbies   []*string `json:"hobbies"`
	UpdatedOn *string   `json:"updatedOn"`
}

type User struct {
	ID        string    `json:"_id"`
	Name      string    `json:"name"`
	Jobtitle  string    `json:"jobtitle"`
	Age       int       `json:"age"`
	City      string    `json:"city"`
	Hobbies   []*string `json:"hobbies"`
	AccountID *string   `json:"accountId"`
	CreatedOn string    `json:"createdOn"`
	UpdatedOn string    `json:"updatedOn"`
}
